import type { NextPage } from "next";
import dynamic from "next/dynamic";

import Head from "next/head";
import { useRouter } from "next/router";
import { useContext, useEffect } from "react";
import { useRecoilState, useRecoilValue } from "recoil";
import { createChatModalState } from "../atoms/createChatModalAtoms";
import { UpdateProfileImageState } from "../atoms/uploadImageAtoms";

import CreateChat from "../components/CreateChat";
import HomeSidebar from "../components/HomeSidebar";
import UpdateModal from "../components/updateModal";
import { AuthContext } from "../context/AuthContext";
import Login from "./login";

const Home: NextPage = () => {
  const user = useContext(AuthContext);
  const [createChatModal] = useRecoilState<boolean>(createChatModalState);
  const [updateProfile] = useRecoilState<boolean>(UpdateProfileImageState);

  return user ? (
    <div>
      <Head>
        <title>zh Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeSidebar />
      </main>
      {updateProfile && <UpdateModal />}
      {createChatModal && <CreateChat />}
    </div>
  ) : (
    <Login />
  );
};

export default Home;
